In [ ]:
%pip install panda
import pandas as pd

In [145]:
pd.set_option('display.max_columns', None)

In [146]:
arquivos = {
    '2020': './esus-vepi.LeitoOcupacao_2020.csv',
    '2021': './esus-vepi.LeitoOcupacao_2021.csv',
    '2022': './esus-vepi.LeitoOcupacao_2022.csv'
}

lista_dataframes = []

for ano, arquivo in arquivos.items():
    try:
        df = pd.read_csv(arquivo, encoding='utf-8')

        df['ano_origem'] = ano

        lista_dataframes.append(df)
    except Exception as e:
        print(f"Erro ao ler os dados do ano {ano}: {e}")


df = pd.concat(lista_dataframes, ignore_index=True) #Concatenando todos os DFs
print(f"Total de linhas no df unificado: {len(df)}")

C:\Users\Davi2\AppData\Local\Temp\ipykernel_16472\4088843205.py:11: DtypeWarning: Columns (0: cnes) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(arquivo, encoding='utf-8')

Total de linhas no df unificado: 1591675

# Análise do dataset

In [147]:
display(df.head(5))
display(df.info())

,Unnamed: 0,_id,dataNotificacao,cnes,ocupacaoSuspeitoCli,ocupacaoSuspeitoUti,ocupacaoConfirmadoCli,ocupacaoConfirmadoUti,ocupacaoCovidUti,ocupacaoCovidCli,ocupacaoHospitalarUti,ocupacaoHospitalarCli,saidaSuspeitaObitos,saidaSuspeitaAltas,saidaConfirmadaObitos,saidaConfirmadaAltas,origem,_p_usuario,estadoNotificacao,municipioNotificacao,estado,municipio,excluido,validado,_created_at,_updated_at,ano_origem
0,0,p5Ez41Zu6B,2020-04-14T03:00:00.000Z,2303167,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,aplicacao-web,_User$auVMjEVEVz,Santa Catarina,Itapema,Santa Catarina,Itapema,True,False,2020-04-15T13:44:30.085Z,2020-04-16T13:56:13.656Z,2020
1,1,eUOMsSt7T7,2020-04-15T03:00:00.000Z,5935377\t,1.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,1.0,0.0,0.0,parse-cloud,_User$WBa5nfe9P9,Rio de Janeiro,Rio de Janeiro,Rio de Janeiro,Rio de Janeiro,False,False,2020-04-15T13:50:47.256Z,2020-08-01T20:08:13.116Z,2020
2,2,QaG4oIBrMa,2020-04-15T14:57:16.255Z,0012599,15.0,1.0,3.0,2.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,parse-cloud,_User$6oxZQHBPQ7,Rio de Janeiro,Niterói,Rio de Janeiro,Niterói,False,False,2020-04-15T15:20:57.033Z,2020-08-01T20:02:12.729Z,2020
3,3,ifya31F3ZF,2020-03-24T03:00:00.000Z,2562871,9.0,0.0,1.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,parse-cloud,_User$fhufIbmR9C,Ceará,Várzea Alegre,Ceará,Várzea Alegre,False,False,2020-04-15T16:58:32.839Z,2020-08-01T21:40:37.624Z,2020
4,4,dkurDhelx9,2020-04-01T03:00:00.000Z,2252228,26.0,0.0,1.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,parse-cloud,_User$tkAdHTNhC9,Rio Grande do Sul,Encantado,Rio Grande do Sul,Encantado,False,False,2020-04-15T17:02:53.877Z,2020-08-01T21:37:53.664Z,2020

<class 'pandas.DataFrame'>
RangeIndex: 1591675 entries, 0 to 1591674
Data columns (total 27 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   Unnamed: 0             1591675 non-null  int64
 1   _id                    1591675 non-null  str
 2   dataNotificacao        1591675 non-null  str
 3   cnes                   1591625 non-null  object
 4   ocupacaoSuspeitoCli    1014964 non-null  float64
 5   ocupacaoSuspeitoUti    1014964 non-null  float64
 6   ocupacaoConfirmadoCli  1014965 non-null  float64
 7   ocupacaoConfirmadoUti  1014965 non-null  float64
 8   ocupacaoCovidUti       583542 non-null   float64
 9   ocupacaoCovidCli       583542 non-null   float64
 10  ocupacaoHospitalarUti  583542 non-null   float64
 11  ocupacaoHospitalarCli  583542 non-null   float64
 12  saidaSuspeitaObitos    1591559 non-null  float64
 13  saidaSuspeitaAltas     1591571 non-null  float64
 14  saidaConfirmadaObitos  1591663 non-null  float64
 15  saidaConfirmadaAltas   1591662 non-null  float64
 16  origem                 1591675 non-null  str
 17  _p_usuario             1591675 non-null  str
 18  estadoNotificacao      1591675 non-null  str
 19  municipioNotificacao   1591675 non-null  str
 20  estado                 1591674 non-null  str
 21  municipio              1591674 non-null  str
 22  excluido               1591675 non-null  bool
 23  validado               1591675 non-null  bool
 24  _created_at            1591675 non-null  str
 25  _updated_at            1591675 non-null  str
 26  ano_origem             1591675 non-null  str
dtypes: bool(2), float64(12), int64(1), object(1), str(11)
memory usage: 306.6+ MB

None

In [148]:
df.nunique(dropna=False)

Unnamed: 0               1591675
_id                      1591675
dataNotificacao           799916
cnes                        7635
ocupacaoSuspeitoCli         1129
ocupacaoSuspeitoUti          554
ocupacaoConfirmadoCli        596
ocupacaoConfirmadoUti        506
ocupacaoCovidUti             225
ocupacaoCovidCli             227
ocupacaoHospitalarUti        330
ocupacaoHospitalarCli        660
saidaSuspeitaObitos          196
saidaSuspeitaAltas           398
saidaConfirmadaObitos        393
saidaConfirmadaAltas        1234
origem                        13
_p_usuario                  3835
estadoNotificacao             28
municipioNotificacao        2353
estado                        29
municipio                   2355
excluido                       2
validado                       1
_created_at              1590872
_updated_at              1590902
ano_origem                     3
dtype: int64

# cnes não inteiro

In [149]:
cnes_num = pd.to_numeric(df['cnes'], errors='coerce')

print("Invalid CNES rows:", cnes_num.isna().sum())
print("Valid CNES rows:", cnes_num.notna().sum())

Invalid CNES rows: 1672
Valid CNES rows: 1590003

In [150]:
cnes_num = pd.to_numeric(df['cnes'], errors='coerce')

df = df[cnes_num.notna()].copy()

df['cnes'] = cnes_num[cnes_num.notna()].astype('int64')

In [151]:
cnes_num = pd.to_numeric(df['cnes'], errors='coerce')

print("Invalid CNES rows:", cnes_num.isna().sum())
print("Valid CNES rows:", cnes_num.notna().sum())

Invalid CNES rows: 0
Valid CNES rows: 1590003

# Valores únicos

Investigando colunas com quantidade razoável de valores únicos

In [152]:
cols = ['origem', 'estado', 'excluido', 'validado']

for col in cols:
    print(f"\n=== {col} ===")
    print(df[col].unique())
    print(f"Quantidade de valores únicos: {df[col].nunique(dropna=False)}")

=== origem ===
<StringArray>
[        'aplicacao-web',           'parse-cloud',                'RPA-SP',
                'RPA-CE',                'RPA-RS',                'RPA-MS',
                'RPA-GO',                'RPA-MT',                'RPA-RN',
                'RPA-PR',                'RPA-MG', 'RPA-MG-BELO-HORIZONTE',
       'RPA-PR-CURITIBA']
Length: 13, dtype: str
Quantidade de valores únicos: 13

=== estado ===
<StringArray>
[     'Santa Catarina',      'Rio de Janeiro',               'Ceará',
   'Rio Grande do Sul',        'Minas Gerais',                'Pará',
               'Piauí',  'Mato Grosso do Sul',               'Goiás',
          'Pernambuco',            'Rondônia',                'Acre',
            'Amazonas',              'Paraná',            'Maranhão',
               'Bahia',           'São Paulo',             'Paraíba',
             'Alagoas',         'Mato Grosso',             'Sergipe',
    'Distrito Federal',           'Tocantins', 'Rio Grande do Norte',
                   nan,               'Amapá',      'Espírito Santo',
             'Roraima',               'GOIAS']
Length: 29, dtype: str
Quantidade de valores únicos: 29

=== excluido ===
[ True False]
Quantidade de valores únicos: 2

=== validado ===
[False]
Quantidade de valores únicos: 1

Observe que a coluna validado tem valor False para todas as entradas logo ela não tem valor e será removida do dataset final

In [153]:
df = df.drop(columns=['validado'])

Os valores RPA-PR-CURITIBA e RPA-MG-BELO-HORIZONTE serão agrupados em RPA-PR e RPA-MG respectivamente

In [154]:
df['origem'] = df['origem'].replace('RPA-PR-CURITIBA', 'RPA-PR')
df['origem'] = df['origem'].replace('RPA-MG-BELO-HORIZONTE', 'RPA-MG')

Ajustar GOIAS para Goiás para ficar padronizado

In [155]:
df['estado'] = df['estado'].replace('GOIAS', 'Goiás')

In [156]:
cols = ['origem', 'estado', 'excluido']

for col in cols:
    print(f"\n=== {col} ===")
    print(df[col].unique())
    print(f"Quantidade de valores únicos: {df[col].nunique(dropna=False)}")

=== origem ===
<StringArray>
['aplicacao-web',   'parse-cloud',        'RPA-SP',        'RPA-CE',
        'RPA-RS',        'RPA-MS',        'RPA-GO',        'RPA-MT',
        'RPA-RN',        'RPA-PR',        'RPA-MG']
Length: 11, dtype: str
Quantidade de valores únicos: 11

=== estado ===
<StringArray>
[     'Santa Catarina',      'Rio de Janeiro',               'Ceará',
   'Rio Grande do Sul',        'Minas Gerais',                'Pará',
               'Piauí',  'Mato Grosso do Sul',               'Goiás',
          'Pernambuco',            'Rondônia',                'Acre',
            'Amazonas',              'Paraná',            'Maranhão',
               'Bahia',           'São Paulo',             'Paraíba',
             'Alagoas',         'Mato Grosso',             'Sergipe',
    'Distrito Federal',           'Tocantins', 'Rio Grande do Norte',
                   nan,               'Amapá',      'Espírito Santo',
             'Roraima']
Length: 28, dtype: str
Quantidade de valores únicos: 28

=== excluido ===
[ True False]
Quantidade de valores únicos: 2

# Tratando NaN

In [157]:
print("Valores ausentes por coluna:")
print(df.isnull().sum())

Valores ausentes por coluna:
Unnamed: 0                     0
_id                            0
dataNotificacao                0
cnes                           0
ocupacaoSuspeitoCli       575215
ocupacaoSuspeitoUti       575215
ocupacaoConfirmadoCli     575214
ocupacaoConfirmadoUti     575214
ocupacaoCovidUti         1007957
ocupacaoCovidCli         1007957
ocupacaoHospitalarUti    1007957
ocupacaoHospitalarCli    1007957
saidaSuspeitaObitos          116
saidaSuspeitaAltas           104
saidaConfirmadaObitos         12
saidaConfirmadaAltas          13
origem                         0
_p_usuario                     0
estadoNotificacao              0
municipioNotificacao           0
estado                         1
municipio                      1
excluido                       0
_created_at                    0
_updated_at                    0
ano_origem                     0
dtype: int64

## cnes nulo

Colunas com cnes nulo serão removidas já que não tem como inferir essa informação.

In [158]:
df['cnes'].isna().sum()

np.int64(0)

In [159]:
df = df.dropna(subset=['cnes'])

In [160]:
df['cnes'].isna().sum()

np.int64(0)

In [161]:
print("Valores ausentes por coluna:")
print(df.isnull().sum())

Valores ausentes por coluna:
Unnamed: 0                     0
_id                            0
dataNotificacao                0
cnes                           0
ocupacaoSuspeitoCli       575215
ocupacaoSuspeitoUti       575215
ocupacaoConfirmadoCli     575214
ocupacaoConfirmadoUti     575214
ocupacaoCovidUti         1007957
ocupacaoCovidCli         1007957
ocupacaoHospitalarUti    1007957
ocupacaoHospitalarCli    1007957
saidaSuspeitaObitos          116
saidaSuspeitaAltas           104
saidaConfirmadaObitos         12
saidaConfirmadaAltas          13
origem                         0
_p_usuario                     0
estadoNotificacao              0
municipioNotificacao           0
estado                         1
municipio                      1
excluido                       0
_created_at                    0
_updated_at                    0
ano_origem                     0
dtype: int64

## Tratamento de NaN para a coluna 'estado'

In [162]:
df[df['estado'].isna()].head()

,Unnamed: 0,_id,dataNotificacao,cnes,ocupacaoSuspeitoCli,ocupacaoSuspeitoUti,ocupacaoConfirmadoCli,ocupacaoConfirmadoUti,ocupacaoCovidUti,ocupacaoCovidCli,ocupacaoHospitalarUti,ocupacaoHospitalarCli,saidaSuspeitaObitos,saidaSuspeitaAltas,saidaConfirmadaObitos,saidaConfirmadaAltas,origem,_p_usuario,estadoNotificacao,municipioNotificacao,estado,municipio,excluido,_created_at,_updated_at,ano_origem
4182,4184,bc66V3say8,2020-04-24T12:32:29.807Z,2246902,1.0,0.0,1.0,0.0,NaN,NaN,NaN,NaN,0.0,1.0,0.0,1.0,aplicacao-web,_User$Ow1jWbSgxK,Rio Grande do Sul,Não-Me-Toque,NaN,NaN,False,2020-04-24T12:33:53.952Z,2020-04-24T12:33:53.952Z,2020

Olhando outras entradas com cnes "2246902" verifica-se que o estado é Rio Grande do Sul e o municipio é Não-Me-Toque.

In [163]:
df[df["cnes"] == 2246902].head()

,Unnamed: 0,_id,dataNotificacao,cnes,ocupacaoSuspeitoCli,ocupacaoSuspeitoUti,ocupacaoConfirmadoCli,ocupacaoConfirmadoUti,ocupacaoCovidUti,ocupacaoCovidCli,ocupacaoHospitalarUti,ocupacaoHospitalarCli,saidaSuspeitaObitos,saidaSuspeitaAltas,saidaConfirmadaObitos,saidaConfirmadaAltas,origem,_p_usuario,estadoNotificacao,municipioNotificacao,estado,municipio,excluido,_created_at,_updated_at,ano_origem
3905,3907,5iesHj3Fzc,2020-04-23T16:46:06.402Z,2246902,5.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,parse-cloud,_User$Ow1jWbSgxK,Rio Grande do Sul,Não-Me-Toque,Rio Grande do Sul,Não-Me-Toque,False,2020-04-23T16:47:02.772Z,2020-08-01T18:55:29.006Z,2020
4182,4184,bc66V3say8,2020-04-24T12:32:29.807Z,2246902,1.0,0.0,1.0,0.0,NaN,NaN,NaN,NaN,0.0,1.0,0.0,1.0,aplicacao-web,_User$Ow1jWbSgxK,Rio Grande do Sul,Não-Me-Toque,NaN,NaN,False,2020-04-24T12:33:53.952Z,2020-04-24T12:33:53.952Z,2020
4185,4187,T5m9LQ3nOz,2020-04-14T03:00:00.000Z,2246902,1.0,0.0,1.0,0.0,NaN,NaN,NaN,NaN,0.0,1.0,0.0,1.0,parse-cloud,_User$Ow1jWbSgxK,Rio Grande do Sul,Não-Me-Toque,Rio Grande do Sul,Não-Me-Toque,False,2020-04-24T12:37:16.319Z,2020-08-01T20:12:50.278Z,2020
4186,4188,MrFGgYzjdJ,2020-04-16T03:00:00.000Z,2246902,1.0,0.0,1.0,0.0,NaN,NaN,NaN,NaN,0.0,1.0,0.0,1.0,parse-cloud,_User$Ow1jWbSgxK,Rio Grande do Sul,Não-Me-Toque,Rio Grande do Sul,Não-Me-Toque,False,2020-04-24T12:37:54.071Z,2020-08-01T19:59:36.523Z,2020
4187,4189,CeWuzFylR1,2020-04-21T03:00:00.000Z,2246902,1.0,0.0,1.0,0.0,NaN,NaN,NaN,NaN,0.0,1.0,0.0,1.0,parse-cloud,_User$Ow1jWbSgxK,Rio Grande do Sul,Não-Me-Toque,Rio Grande do Sul,Não-Me-Toque,False,2020-04-24T12:38:22.763Z,2020-08-01T19:19:18.653Z,2020

In [164]:
df.loc[
    df['cnes'] == '2246902',
    ['estado', 'municipio']
] = ['Rio Grande do Sul', 'Não-Me-Toque']

In [165]:
df[df['estado'].isna()].head()

,Unnamed: 0,_id,dataNotificacao,cnes,ocupacaoSuspeitoCli,ocupacaoSuspeitoUti,ocupacaoConfirmadoCli,ocupacaoConfirmadoUti,ocupacaoCovidUti,ocupacaoCovidCli,ocupacaoHospitalarUti,ocupacaoHospitalarCli,saidaSuspeitaObitos,saidaSuspeitaAltas,saidaConfirmadaObitos,saidaConfirmadaAltas,origem,_p_usuario,estadoNotificacao,municipioNotificacao,estado,municipio,excluido,_created_at,_updated_at,ano_origem
4182,4184,bc66V3say8,2020-04-24T12:32:29.807Z,2246902,1.0,0.0,1.0,0.0,NaN,NaN,NaN,NaN,0.0,1.0,0.0,1.0,aplicacao-web,_User$Ow1jWbSgxK,Rio Grande do Sul,Não-Me-Toque,NaN,NaN,False,2020-04-24T12:33:53.952Z,2020-04-24T12:33:53.952Z,2020

## saída

df[df['saidaConfirmadaObitos'].isna()].head()

In [166]:
df[df['saidaConfirmadaObitos'].isna()].head(50)

,Unnamed: 0,_id,dataNotificacao,cnes,ocupacaoSuspeitoCli,ocupacaoSuspeitoUti,ocupacaoConfirmadoCli,ocupacaoConfirmadoUti,ocupacaoCovidUti,ocupacaoCovidCli,ocupacaoHospitalarUti,ocupacaoHospitalarCli,saidaSuspeitaObitos,saidaSuspeitaAltas,saidaConfirmadaObitos,saidaConfirmadaAltas,origem,_p_usuario,estadoNotificacao,municipioNotificacao,estado,municipio,excluido,_created_at,_updated_at,ano_origem
29249,29260,Pb3Z5MezCQ,2020-05-18T14:02:41.949Z,2012766,15.0,1.0,1.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,parse-cloud,_User$kESz5jJHJr,Amazonas,Manaus,Amazonas,Manaus,False,2020-05-18T14:04:20.066Z,2020-08-01T12:03:39.961Z,2020
29257,29268,vwOdDwIsyX,2020-05-18T14:02:41.949Z,2012766,15.0,1.0,1.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,parse-cloud,_User$kESz5jJHJr,Amazonas,Manaus,Amazonas,Manaus,False,2020-05-18T14:05:32.277Z,2020-08-01T12:03:38.649Z,2020
29258,29269,rvG7MhMwhD,2020-05-18T14:02:41.949Z,2012766,15.0,1.0,1.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,parse-cloud,_User$kESz5jJHJr,Amazonas,Manaus,Amazonas,Manaus,False,2020-05-18T14:07:58.038Z,2020-08-01T12:03:37.839Z,2020
29259,29270,NAHmolhvf6,2020-05-18T14:02:41.949Z,2012766,15.0,1.0,1.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,parse-cloud,_User$kESz5jJHJr,Amazonas,Manaus,Amazonas,Manaus,False,2020-05-18T14:07:51.148Z,2020-08-01T12:03:36.510Z,2020
29272,29283,DCQJOQoyWU,2020-05-18T14:02:41.949Z,2012766,15.0,1.0,1.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,parse-cloud,_User$kESz5jJHJr,Amazonas,Manaus,Amazonas,Manaus,False,2020-05-18T14:07:36.792Z,2020-08-01T12:03:34.852Z,2020
45567,45586,bZKmcbG4Ql,2020-05-28T03:00:00.000Z,2081253,35.0,12.0,10.0,3.0,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,parse-cloud,_User$Wc8lJNxzUO,São Paulo,Araras,São Paulo,Araras,False,2020-05-29T11:56:24.669Z,2020-08-01T08:07:05.736Z,2020
140248,140281,pLsyCdJYaS,2020-07-11T03:00:00.000Z,2561395,42.0,0.0,2.0,0.0,NaN,NaN,NaN,NaN,0.0,1.0,NaN,NaN,parse-cloud,_User$bkiCmE6DHy,Ceará,Aquiraz,Ceará,Aquiraz,False,2020-07-20T17:52:57.213Z,2020-07-31T18:42:48.564Z,2020
140252,140285,baBV97tRls,2020-07-12T03:00:00.000Z,2561395,42.0,0.0,2.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,parse-cloud,_User$bkiCmE6DHy,Ceará,Aquiraz,Ceará,Aquiraz,False,2020-07-20T17:53:22.299Z,2020-07-31T18:22:33.675Z,2020
140258,140291,pZ1kZD8neJ,2020-07-13T03:00:00.000Z,2561395,42.0,0.0,2.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,parse-cloud,_User$bkiCmE6DHy,Ceará,Aquiraz,Ceará,Aquiraz,False,2020-07-20T17:53:37.366Z,2020-07-31T18:02:19.879Z,2020
140260,140293,0TAzVjuIHr,2020-07-14T03:00:00.000Z,2561395,42.0,0.0,1.0,0.0,NaN,NaN,NaN,NaN,1.0,0.0,NaN,NaN,parse-cloud,_User$bkiCmE6DHy,Ceará,Aquiraz,Ceará,Aquiraz,False,2020-07-20T17:53:55.205Z,2020-07-31T17:39:47.756Z,2020
140265,140298,nSPQI6s35k,2020-07-15T03:00:00.000Z,2561395,42.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,2.0,NaN,NaN,parse-cloud,_User$bkiCmE6DHy,Ceará,Aquiraz,Ceará,Aquiraz,False,2020-07-20T17:54:38.664Z,2020-07-31T17:17:26.658Z,2020
140267,140300,U2gRcWbmgf,2020-07-16T03:00:00.000Z,2561395,42.0,0.0,2.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,parse-cloud,_User$bkiCmE6DHy,Ceará,Aquiraz,Ceará,Aquiraz,False,2020-07-20T17:55:06.852Z,2020-07-31T16:59:22.003Z,2020

In [167]:
df[df["cnes"] == 2012766].head(50)

,Unnamed: 0,_id,dataNotificacao,cnes,ocupacaoSuspeitoCli,ocupacaoSuspeitoUti,ocupacaoConfirmadoCli,ocupacaoConfirmadoUti,ocupacaoCovidUti,ocupacaoCovidCli,ocupacaoHospitalarUti,ocupacaoHospitalarCli,saidaSuspeitaObitos,saidaSuspeitaAltas,saidaConfirmadaObitos,saidaConfirmadaAltas,origem,_p_usuario,estadoNotificacao,municipioNotificacao,estado,municipio,excluido,_created_at,_updated_at,ano_origem
14379,14383,T6uyj8YTzd,2020-05-05T16:23:42.983Z,2012766,15.0,1.0,8.0,0.0,NaN,NaN,NaN,NaN,1.0,0.0,1.0,2.0,parse-cloud,_User$0Ik365If7Z,Amazonas,Manaus,Amazonas,Manaus,False,2020-05-05T16:31:44.431Z,2020-08-01T16:26:45.559Z,2020
15098,15102,SK9jgoXpjr,2020-05-06T13:51:37.914Z,2012766,15.0,1.0,6.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,1.0,2.0,parse-cloud,_User$kESz5jJHJr,Amazonas,Manaus,Amazonas,Manaus,False,2020-05-06T13:53:52.540Z,2020-08-01T16:14:07.844Z,2020
17494,17498,xMxDujkHzz,2020-05-08T16:59:55.064Z,2012766,15.0,1.0,13.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,1.0,0.0,parse-cloud,_User$0Ik365If7Z,Amazonas,Manaus,Amazonas,Manaus,False,2020-05-08T17:00:47.427Z,2020-08-01T15:37:57.486Z,2020
21222,21231,pG5iPS1RiP,2020-05-12T14:00:06.715Z,2012766,15.0,1.0,3.0,0.0,NaN,NaN,NaN,NaN,1.0,0.0,0.0,0.0,parse-cloud,_User$kESz5jJHJr,Amazonas,Manaus,Amazonas,Manaus,False,2020-05-12T14:01:02.063Z,2020-08-01T14:19:06.868Z,2020
22853,22862,ta7HYBOfm7,2020-05-13T14:09:42.419Z,2012766,15.0,1.0,3.0,0.0,NaN,NaN,NaN,NaN,0.0,3.0,0.0,1.0,parse-cloud,_User$0Ik365If7Z,Amazonas,Manaus,Amazonas,Manaus,False,2020-05-13T14:10:34.198Z,2020-08-01T13:56:33.985Z,2020
24459,24468,6HiAKIwZef,2020-05-14T14:43:03.417Z,2012766,15.0,1.0,1.0,0.0,NaN,NaN,NaN,NaN,1.0,0.0,0.0,0.0,parse-cloud,_User$0Ik365If7Z,Amazonas,Manaus,Amazonas,Manaus,False,2020-05-14T15:03:48.337Z,2020-08-01T13:33:09.283Z,2020
25783,25794,Vy1J9DwBkC,2020-05-15T13:28:14.278Z,2012766,15.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,parse-cloud,_User$kESz5jJHJr,Amazonas,Manaus,Amazonas,Manaus,False,2020-05-15T13:30:31.962Z,2020-08-01T13:11:27.110Z,2020
27888,27899,bdAYe0SVu7,2020-05-17T13:09:47.444Z,2012766,15.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,parse-cloud,_User$0Ik365If7Z,Amazonas,Manaus,Amazonas,Manaus,False,2020-05-17T13:10:18.213Z,2020-08-01T12:27:22.077Z,2020
29249,29260,Pb3Z5MezCQ,2020-05-18T14:02:41.949Z,2012766,15.0,1.0,1.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,parse-cloud,_User$kESz5jJHJr,Amazonas,Manaus,Amazonas,Manaus,False,2020-05-18T14:04:20.066Z,2020-08-01T12:03:39.961Z,2020
29257,29268,vwOdDwIsyX,2020-05-18T14:02:41.949Z,2012766,15.0,1.0,1.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,parse-cloud,_User$kESz5jJHJr,Amazonas,Manaus,Amazonas,Manaus,False,2020-05-18T14:05:32.277Z,2020-08-01T12:03:38.649Z,2020
29258,29269,rvG7MhMwhD,2020-05-18T14:02:41.949Z,2012766,15.0,1.0,1.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,parse-cloud,_User$kESz5jJHJr,Amazonas,Manaus,Amazonas,Manaus,False,2020-05-18T14:07:58.038Z,2020-08-01T12:03:37.839Z,2020
29259,29270,NAHmolhvf6,2020-05-18T14:02:41.949Z,2012766,15.0,1.0,1.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,parse-cloud,_User$kESz5jJHJr,Amazonas,Manaus,Amazonas,Manaus,False,2020-05-18T14:07:51.148Z,2020-08-01T12:03:36.510Z,2020
29272,29283,DCQJOQoyWU,2020-05-18T14:02:41.949Z,2012766,15.0,1.0,1.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,parse-cloud,_User$kESz5jJHJr,Amazonas,Manaus,Amazonas,Manaus,False,2020-05-18T14:07:36.792Z,2020-08-01T12:03:34.852Z,2020
30920,30931,GumZZFeKfQ,2020-05-19T13:00:09.663Z,2012766,15.0,1.0,1.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,1.0,parse-cloud,_User$0Ik365If7Z,Amazonas,Manaus,Amazonas,Manaus,False,2020-05-19T13:02:08.094Z,2020-08-01T11:39:28.388Z,2020
32607,32618,KPVS4ShNIZ,2020-05-20T13:07:41.616Z,2012766,15.0,1.0,2.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,parse-cloud,_User$0Ik365If7Z,Amazonas,Manaus,Amazonas,Manaus,False,2020-05-20T13:09:03.731Z,2020-08-01T11:16:49.289Z,2020
33967,33978,47uz4BHIls,2020-05-21T13:01:29.626Z,2012766,15.0,1.0,2.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,parse-cloud,_User$kESz5jJHJr,Amazonas,Manaus,Amazonas,Manaus,False,2020-05-21T13:02:16.843Z,2020-08-01T10:54:18.900Z,2020
35543,35554,DOB88qBFV2,2020-05-22T13:02:52.154Z,2012766,16.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,parse-cloud,_User$0Ik365If7Z,Amazonas,Manaus,Amazonas,Manaus,False,2020-05-22T13:04:55.839Z,2020-08-01T10:31:26.514Z,2020
35544,35555,TU5KENrRp6,2020-05-22T13:02:52.154Z,2012766,16.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,parse-cloud,_User$0Ik365If7Z,Amazonas,Manaus,Amazonas,Manaus,False,2020-05-22T13:05:40.566Z,2020-08-01T10:31:25.678Z,2020
35545,35556,kcSPy0Ue1Y,2020-05-22T13:05:56.225Z,2012766,16.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,parse-cloud,_User$0Ik365If7Z,Amazonas,Manaus,Amazonas,Manaus,False,2020-05-22T13:06:35.428Z,2020-08-01T10:31:20.594Z,2020
36692,36703,SS16Pcj9sB,2020-05-23T12:44:40.769Z,2012766,16.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,parse-cloud,_User$0Ik365If7Z,Amazonas,Manaus,Amazonas,Manaus,False,2020-05-23T12:47:57.929Z,2020-08-01T10:09:09.119Z,2020
37571,37582,cLGDCgAWrq,2020-05-24T12:59:11.950Z,2012766,16.0,0.0,1.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,parse-cloud,_User$kESz5jJHJr,Amazonas,Manaus,Amazonas,Manaus,False,2020-05-24T12:59:42.709Z,2020-08-01T09:47:37.079Z,2020
38842,38853,oZp94lA0lh,2020-05-25T13:16:30.240Z,2012766,16.0,0.0,1.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,parse-cloud,_User$0Ik365If7Z,Amazonas,Manaus,Amazonas,Manaus,False,2020-05-25T13:18:24.340Z,2020-08-01T09:26:02.619Z,2020
41195,41207,W49M8qRdAU,2020-05-26T14:53:55.278Z,2012766,16.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,parse-cloud,_User$0Ik365If7Z,Amazonas,Manaus,Amazonas,Manaus,False,2020-05-26T14:54:42.818Z,2020-08-01T08:56:48.385Z,2020
41202,41214,VBBUAgQxl3,2020-05-26T14:53:55.278Z,2012766,16.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,parse-cloud,_User$0Ik365If7Z,Amazonas,Manaus,Amazonas,Manaus,False,2020-05-26T14:56:03.477Z,2020-08-01T08:56:47.622Z,2020
41205,41217,KgA03yxPzv,2020-05-26T14:53:55.278Z,2012766,16.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,parse-cloud,_User$0Ik365If7Z,Amazonas,Manaus,Amazonas,Manaus,False,2020-05-26T14:57:17.262Z,2020-08-01T08:56:46.642Z,2020
41208,41220,dZUZLr3F7a,2020-05-26T14:53:55.278Z,2012766,16.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,parse-cloud,_User$0Ik365If7Z,Amazonas,Manaus,Amazonas,Manaus,False,2020-05-26T14:57:02.236Z,2020-08-01T08:56:45.524Z,2020
41227,41239,01ZrEegX1U,2020-05-26T15:05:56.266Z,2012766,16.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,parse-cloud,_User$0Ik365If7Z,Amazonas,Manaus,Amazonas,Manaus,False,2020-05-26T15:06:33.275Z,2020-08-01T08:56:25.140Z,2020
42632,42651,1K2Pmfw8Zf,2020-05-27T12:49:03.511Z,2012766,16.0,0.0,1.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,parse-cloud,_User$kESz5jJHJr,Amazonas,Manaus,Amazonas,Manaus,False,2020-05-27T12:49:23.626Z,2020-08-01T08:34:13.663Z,2020
44404,44423,3KD7p2x0b7,2020-05-28T14:22:55.010Z,2012766,16.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,parse-cloud,_User$0Ik365If7Z,Amazonas,Manaus,Amazonas,Manaus,False,2020-05-28T14:23:30.304Z,2020-08-01T07:55:47.645Z,2020
45691,45710,hPPmLSaY2p,2020-05-29T12:30:08.454Z,2012766,16.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,parse-cloud,_User$0Ik365If7Z,Amazonas,Manaus,Amazonas,Manaus,False,2020-05-29T12:30:40.255Z,2020-08-01T07:37:54.311Z,2020
47113,47133,6TIaT7dKbD,2020-05-30T13:05:24.247Z,2012766,16.0,0.0,1.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,parse-cloud,_User$kESz5jJHJr,Amazonas,Manaus,Amazonas,Manaus,False,2020-05-30T13:05:54.301Z,2020-08-01T07:16:58.891Z,2020
47958,47979,ijyET1oPM7,2020-05-31T13:14:44.620Z,2012766,16.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,-1.0,0.0,0.0,parse-cloud,_User$0Ik365If7Z,Amazonas,Manaus,Amazonas,Manaus,False,2020-05-31T12:54:09.213Z,2020-08-01T06:59:05.141Z,2020
49128,49149,2gtzfC5veZ,2020-06-01T13:04:36.081Z,2012766,16.0,0.0,1.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,parse-cloud,_User$0Ik365If7Z,Amazonas,Manaus,Amazonas,Manaus,False,2020-06-01T12:43:55.754Z,2020-08-01T06:41:40.245Z,2020
51135,51157,OrIFc1yAnm,2020-06-02T13:42:43.674Z,2012766,16.0,0.0,1.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,parse-cloud,_User$0Ik365If7Z,Amazonas,Manaus,Amazonas,Manaus,False,2020-06-02T13:43:29.129Z,2020-08-01T06:21:37.630Z,2020
52798,52820,3wIRvBpLy6,2020-06-03T12:31:39.996Z,2012766,16.0,0.0,2.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,parse-cloud,_User$kESz5jJHJr,Amazonas,Manaus,Amazonas,Manaus,False,2020-06-03T12:32:09.951Z,2020-08-01T06:03:48.804Z,2020
55331,55353,7UF22xIuhP,2020-06-04T13:22:59.011Z,2012766,16.0,0.0,1.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,parse-cloud,_User$0Ik365If7Z,Amazonas,Manaus,Amazonas,Manaus,False,2020-06-04T13:23:47.720Z,2020-08-01T05:44:36.930Z,2020
57469,57491,tgWIyD5Vh1,2020-06-05T12:26:57.421Z,2012766,16.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,parse-cloud,_User$kESz5jJHJr,Amazonas,Manaus,Amazonas,Manaus,False,2020-06-05T12:27:35.987Z,2020-08-01T05:27:47.508Z,2020
58867,58890,mzGgJFJJQv,2020-06-06T12:59:55.050Z,2012766,16.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,parse-cloud,_User$0Ik365If7Z,Amazonas,Manaus,Amazonas,Manaus,False,2020-06-06T12:49:30.596Z,2020-08-01T05:08:42.616Z,2020
59769,59794,Qgumv6Rq8F,2020-06-07T12:55:43.230Z,2012766,16.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,parse-cloud,_User$kESz5jJHJr,Amazonas,Manaus,Amazonas,Manaus,False,2020-06-07T12:58:15.501Z,2020-08-01T04:52:32.166Z,2020
61097,61122,DTslIBSKzM,2020-06-08T13:02:15.344Z,2012766,16.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,parse-cloud,_User$0Ik365If7Z,Amazonas,Manaus,Amazonas,Manaus,False,2020-06-08T13:02:36.365Z,2020-08-01T04:37:23.763Z,2020
63153,63179,02xb3zSjaK,2020-06-09T14:06:19.360Z,2012766,16.0,0.0,1.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,parse-cloud,_User$0Ik365If7Z,Amazonas,Manaus,Amazonas,Manaus,False,2020-06-09T13:41:14.692Z,2020-08-01T04:17:29.181Z,2020
64742,64768,L3CU4QCnmn,2020-06-10T13:10:24.462Z,2012766,16.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,parse-cloud,_User$0Ik365If7Z,Amazonas,Manaus,Amazonas,Manaus,False,2020-06-10T13:10:44.428Z,2020-08-01T03:59:07.499Z,2020
66135,66162,qS5rsknCMN,2020-06-11T12:21:50.590Z,2012766,16.0,0.0,2.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,parse-cloud,_User$kESz5jJHJr,Amazonas,Manaus,Amazonas,Manaus,False,2020-06-11T12:40:48.349Z,2020-08-01T03:39:51.201Z,2020
67233,67261,QHKVeOXlry,2020-06-12T12:40:01.780Z,2012766,16.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,parse-cloud,_User$0Ik365If7Z,Amazonas,Manaus,Amazonas,Manaus,False,2020-06-12T12:16:43.518Z,2020-08-01T03:21:43.695Z,2020
68525,68553,TVfuzoPHd1,2020-06-13T12:40:02.896Z,2012766,16.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,parse-cloud,_User$0Ik365If7Z,Amazonas,Manaus,Amazonas,Manaus,False,2020-06-13T12:40:21.270Z,2020-08-01T03:03:56.225Z,2020
69526,69554,eisM074gD1,2020-06-14T13:30:34.372Z,2012766,16.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,parse-cloud,_User$0Ik365If7Z,Amazonas,Manaus,Amazonas,Manaus,False,2020-06-14T13:32:13.850Z,2020-08-01T02:46:31.284Z,2020
70707,70735,rsXszh9f0H,2020-06-15T12:41:11.479Z,2012766,16.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,parse-cloud,_User$kESz5jJHJr,Amazonas,Manaus,Amazonas,Manaus,False,2020-06-15T12:41:35.252Z,2020-08-01T02:31:35.256Z,2020
72745,72773,fBhCkbieUv,2020-06-16T12:38:19.019Z,2012766,16.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,parse-cloud,_User$0Ik365If7Z,Amazonas,Manaus,Amazonas,Manaus,False,2020-06-16T12:41:50.905Z,2020-08-01T02:13:41.633Z,2020
74368,74396,64YFXgAYBf,2020-06-17T12:33:06.128Z,2012766,16.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,parse-cloud,_User$kESz5jJHJr,Amazonas,Manaus,Amazonas,Manaus,False,2020-06-17T12:52:01.368Z,2020-08-01T01:56:41.178Z,2020
75782,75810,6E1dvpzn0N,2020-06-18T13:09:06.393Z,2012766,16.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,1.0,parse-cloud,_User$0Ik365If7Z,Amazonas,Manaus,Amazonas,Manaus,False,2020-06-18T12:45:16.401Z,2020-08-01T01:39:17.168Z,2020

Para as colunas de saída talvez fosse possível calcular o valor olhando a queda para os valores de ocupação dos leitos, mas de 123170 para 124387 o número de ocupaçãoconfirmadoCli diminuiu sem valor para saída, logo as entradas que tem valor nulo para saidaSuspeitaObitos (116), saidaSuspeitaAltas (104), saidaConfirmadaObitos (12) e saidaConfirmadaAltas(13) serão removidas , além disso elas não são um número muito significativo para o volume de dados em geral.

In [168]:
print(df['saidaSuspeitaObitos'].isna().sum())
print(df['saidaSuspeitaAltas'].isna().sum())
print(df['saidaConfirmadaObitos'].isna().sum())
print(df['saidaConfirmadaAltas'].isna().sum())

116
104
12
13

In [169]:
df = df.dropna(subset=['saidaSuspeitaObitos'])
df = df.dropna(subset=['saidaSuspeitaAltas'])
df = df.dropna(subset=['saidaConfirmadaObitos'])
df = df.dropna(subset=['saidaConfirmadaAltas'])

In [170]:
print(df['saidaSuspeitaObitos'].isna().sum())
print(df['saidaSuspeitaAltas'].isna().sum())
print(df['saidaConfirmadaObitos'].isna().sum())
print(df['saidaConfirmadaAltas'].isna().sum())

0
0
0
0

## Ocupacao Covid

Para os valores de 2020 e 2021, as ocupações dos leitos eram divididas em ocupação por suspeita e ocupação quando o diagnóstico de COVID era confirmado, isso levou ao grande número de NaNs nas colunas referentes às ocupações dos leitos, para resolver isso os campos NaN de ocupacaoCovidUti e ocupacaoCovidCli somando ocupacaoSuspeito e ocupacaoConfirmado para Cli ou UTI correspondentemente

In [171]:
mask = (
    df['ano_origem'].isin(['2020', '2021']) &
    df['ocupacaoCovidUti'].isna()
)

df.loc[mask, 'ocupacaoCovidUti'] = (
    df.loc[mask, 'ocupacaoSuspeitoUti'].fillna(0) +
    df.loc[mask, 'ocupacaoConfirmadoUti'].fillna(0)
)

mask = (
    df['ano_origem'].isin(['2020', '2021']) &
    df['ocupacaoCovidCli'].isna()
)

df.loc[mask, 'ocupacaoCovidCli'] = (
    df.loc[mask, 'ocupacaoSuspeitoCli'].fillna(0) +
    df.loc[mask, 'ocupacaoConfirmadoCli'].fillna(0)
)

In [172]:
df.head()

,Unnamed: 0,_id,dataNotificacao,cnes,ocupacaoSuspeitoCli,ocupacaoSuspeitoUti,ocupacaoConfirmadoCli,ocupacaoConfirmadoUti,ocupacaoCovidUti,ocupacaoCovidCli,ocupacaoHospitalarUti,ocupacaoHospitalarCli,saidaSuspeitaObitos,saidaSuspeitaAltas,saidaConfirmadaObitos,saidaConfirmadaAltas,origem,_p_usuario,estadoNotificacao,municipioNotificacao,estado,municipio,excluido,_created_at,_updated_at,ano_origem
0,0,p5Ez41Zu6B,2020-04-14T03:00:00.000Z,2303167,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,aplicacao-web,_User$auVMjEVEVz,Santa Catarina,Itapema,Santa Catarina,Itapema,True,2020-04-15T13:44:30.085Z,2020-04-16T13:56:13.656Z,2020
1,1,eUOMsSt7T7,2020-04-15T03:00:00.000Z,5935377,1.0,0.0,0.0,0.0,0.0,1.0,NaN,NaN,0.0,1.0,0.0,0.0,parse-cloud,_User$WBa5nfe9P9,Rio de Janeiro,Rio de Janeiro,Rio de Janeiro,Rio de Janeiro,False,2020-04-15T13:50:47.256Z,2020-08-01T20:08:13.116Z,2020
2,2,QaG4oIBrMa,2020-04-15T14:57:16.255Z,12599,15.0,1.0,3.0,2.0,3.0,18.0,NaN,NaN,0.0,0.0,0.0,0.0,parse-cloud,_User$6oxZQHBPQ7,Rio de Janeiro,Niterói,Rio de Janeiro,Niterói,False,2020-04-15T15:20:57.033Z,2020-08-01T20:02:12.729Z,2020
3,3,ifya31F3ZF,2020-03-24T03:00:00.000Z,2562871,9.0,0.0,1.0,0.0,0.0,10.0,NaN,NaN,0.0,0.0,0.0,0.0,parse-cloud,_User$fhufIbmR9C,Ceará,Várzea Alegre,Ceará,Várzea Alegre,False,2020-04-15T16:58:32.839Z,2020-08-01T21:40:37.624Z,2020
4,4,dkurDhelx9,2020-04-01T03:00:00.000Z,2252228,26.0,0.0,1.0,0.0,0.0,27.0,NaN,NaN,0.0,0.0,0.0,0.0,parse-cloud,_User$tkAdHTNhC9,Rio Grande do Sul,Encantado,Rio Grande do Sul,Encantado,False,2020-04-15T17:02:53.877Z,2020-08-01T21:37:53.664Z,2020

In [173]:
print("Valores ausentes por coluna:")
print(df.isnull().sum())

Valores ausentes por coluna:
Unnamed: 0                     0
_id                            0
dataNotificacao                0
cnes                           0
ocupacaoSuspeitoCli       575203
ocupacaoSuspeitoUti       575203
ocupacaoConfirmadoCli     575202
ocupacaoConfirmadoUti     575202
ocupacaoCovidUti               0
ocupacaoCovidCli               0
ocupacaoHospitalarUti    1007840
ocupacaoHospitalarCli    1007840
saidaSuspeitaObitos            0
saidaSuspeitaAltas             0
saidaConfirmadaObitos          0
saidaConfirmadaAltas           0
origem                         0
_p_usuario                     0
estadoNotificacao              0
municipioNotificacao           0
estado                         1
municipio                      1
excluido                       0
_created_at                    0
_updated_at                    0
ano_origem                     0
dtype: int64

# Tipo de dados

Alterar o tipo de dataNotificao,created_at e updated_at para datetime64, assim essa coluna poderá ser usada para gerar Dia, Mês e Hora.

In [174]:
df['dataNotificacao'] = pd.to_datetime(df['dataNotificacao'])
df['dataCriado'] = pd.to_datetime(df['_created_at'])
df['dataAtualizado'] = pd.to_datetime(df['_updated_at'])

In [175]:
df['dia_notificacao'] = df['dataNotificacao'].dt.day
df['mes_notificacao'] = df['dataNotificacao'].dt.month
df['hora_notificao'] = pd.to_datetime(df['dataNotificacao']).dt.time

df['dia_criado'] = df['dataCriado'].dt.day
df['mes_criado'] = df['dataCriado'].dt.month
df['hora_criado'] = pd.to_datetime(df['dataCriado']).dt.time

df['dia_atualizado'] = df['dataAtualizado'].dt.day
df['mes_atualizado'] = df['dataAtualizado'].dt.month
df['hora_atualizado'] = pd.to_datetime(df['dataAtualizado']).dt.time

In [176]:
df.head()

,Unnamed: 0,_id,dataNotificacao,cnes,ocupacaoSuspeitoCli,ocupacaoSuspeitoUti,ocupacaoConfirmadoCli,ocupacaoConfirmadoUti,ocupacaoCovidUti,ocupacaoCovidCli,ocupacaoHospitalarUti,ocupacaoHospitalarCli,saidaSuspeitaObitos,saidaSuspeitaAltas,saidaConfirmadaObitos,saidaConfirmadaAltas,origem,_p_usuario,estadoNotificacao,municipioNotificacao,estado,municipio,excluido,_created_at,_updated_at,ano_origem,dataCriado,dataAtualizado,dia_notificacao,mes_notificacao,hora_notificao,dia_criado,mes_criado,hora_criado,dia_atualizado,mes_atualizado,hora_atualizado
0,0,p5Ez41Zu6B,2020-04-14 03:00:00+00:00,2303167,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,aplicacao-web,_User$auVMjEVEVz,Santa Catarina,Itapema,Santa Catarina,Itapema,True,2020-04-15T13:44:30.085Z,2020-04-16T13:56:13.656Z,2020,2020-04-15 13:44:30.085000+00:00,2020-04-16 13:56:13.656000+00:00,14,4,03:00:00,15,4,13:44:30.085000,16,4,13:56:13.656000
1,1,eUOMsSt7T7,2020-04-15 03:00:00+00:00,5935377,1.0,0.0,0.0,0.0,0.0,1.0,NaN,NaN,0.0,1.0,0.0,0.0,parse-cloud,_User$WBa5nfe9P9,Rio de Janeiro,Rio de Janeiro,Rio de Janeiro,Rio de Janeiro,False,2020-04-15T13:50:47.256Z,2020-08-01T20:08:13.116Z,2020,2020-04-15 13:50:47.256000+00:00,2020-08-01 20:08:13.116000+00:00,15,4,03:00:00,15,4,13:50:47.256000,1,8,20:08:13.116000
2,2,QaG4oIBrMa,2020-04-15 14:57:16.255000+00:00,12599,15.0,1.0,3.0,2.0,3.0,18.0,NaN,NaN,0.0,0.0,0.0,0.0,parse-cloud,_User$6oxZQHBPQ7,Rio de Janeiro,Niterói,Rio de Janeiro,Niterói,False,2020-04-15T15:20:57.033Z,2020-08-01T20:02:12.729Z,2020,2020-04-15 15:20:57.033000+00:00,2020-08-01 20:02:12.729000+00:00,15,4,14:57:16.255000,15,4,15:20:57.033000,1,8,20:02:12.729000
3,3,ifya31F3ZF,2020-03-24 03:00:00+00:00,2562871,9.0,0.0,1.0,0.0,0.0,10.0,NaN,NaN,0.0,0.0,0.0,0.0,parse-cloud,_User$fhufIbmR9C,Ceará,Várzea Alegre,Ceará,Várzea Alegre,False,2020-04-15T16:58:32.839Z,2020-08-01T21:40:37.624Z,2020,2020-04-15 16:58:32.839000+00:00,2020-08-01 21:40:37.624000+00:00,24,3,03:00:00,15,4,16:58:32.839000,1,8,21:40:37.624000
4,4,dkurDhelx9,2020-04-01 03:00:00+00:00,2252228,26.0,0.0,1.0,0.0,0.0,27.0,NaN,NaN,0.0,0.0,0.0,0.0,parse-cloud,_User$tkAdHTNhC9,Rio Grande do Sul,Encantado,Rio Grande do Sul,Encantado,False,2020-04-15T17:02:53.877Z,2020-08-01T21:37:53.664Z,2020,2020-04-15 17:02:53.877000+00:00,2020-08-01 21:37:53.664000+00:00,1,4,03:00:00,15,4,17:02:53.877000,1,8,21:37:53.664000

In [189]:
df = df.rename(columns={'dataNotificacao': 'data_notificacao'})
df = df.rename(columns={'_created_at': 'created_at'})
df = df.rename(columns={'_updated_at': 'updated_at'})

# Removendo colunas

In [178]:
df.head()

,Unnamed: 0,_id,data_notificacao,cnes,ocupacaoSuspeitoCli,ocupacaoSuspeitoUti,ocupacaoConfirmadoCli,ocupacaoConfirmadoUti,ocupacaoCovidUti,ocupacaoCovidCli,ocupacaoHospitalarUti,ocupacaoHospitalarCli,saidaSuspeitaObitos,saidaSuspeitaAltas,saidaConfirmadaObitos,saidaConfirmadaAltas,origem,_p_usuario,estadoNotificacao,municipioNotificacao,estado,municipio,excluido,_created_at,_updated_at,ano_origem,dataCriado,dataAtualizado,dia_notificacao,mes_notificacao,hora_notificao,dia_criado,mes_criado,hora_criado,dia_atualizado,mes_atualizado,hora_atualizado
0,0,p5Ez41Zu6B,2020-04-14 03:00:00+00:00,2303167,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,aplicacao-web,_User$auVMjEVEVz,Santa Catarina,Itapema,Santa Catarina,Itapema,True,2020-04-15T13:44:30.085Z,2020-04-16T13:56:13.656Z,2020,2020-04-15 13:44:30.085000+00:00,2020-04-16 13:56:13.656000+00:00,14,4,03:00:00,15,4,13:44:30.085000,16,4,13:56:13.656000
1,1,eUOMsSt7T7,2020-04-15 03:00:00+00:00,5935377,1.0,0.0,0.0,0.0,0.0,1.0,NaN,NaN,0.0,1.0,0.0,0.0,parse-cloud,_User$WBa5nfe9P9,Rio de Janeiro,Rio de Janeiro,Rio de Janeiro,Rio de Janeiro,False,2020-04-15T13:50:47.256Z,2020-08-01T20:08:13.116Z,2020,2020-04-15 13:50:47.256000+00:00,2020-08-01 20:08:13.116000+00:00,15,4,03:00:00,15,4,13:50:47.256000,1,8,20:08:13.116000
2,2,QaG4oIBrMa,2020-04-15 14:57:16.255000+00:00,12599,15.0,1.0,3.0,2.0,3.0,18.0,NaN,NaN,0.0,0.0,0.0,0.0,parse-cloud,_User$6oxZQHBPQ7,Rio de Janeiro,Niterói,Rio de Janeiro,Niterói,False,2020-04-15T15:20:57.033Z,2020-08-01T20:02:12.729Z,2020,2020-04-15 15:20:57.033000+00:00,2020-08-01 20:02:12.729000+00:00,15,4,14:57:16.255000,15,4,15:20:57.033000,1,8,20:02:12.729000
3,3,ifya31F3ZF,2020-03-24 03:00:00+00:00,2562871,9.0,0.0,1.0,0.0,0.0,10.0,NaN,NaN,0.0,0.0,0.0,0.0,parse-cloud,_User$fhufIbmR9C,Ceará,Várzea Alegre,Ceará,Várzea Alegre,False,2020-04-15T16:58:32.839Z,2020-08-01T21:40:37.624Z,2020,2020-04-15 16:58:32.839000+00:00,2020-08-01 21:40:37.624000+00:00,24,3,03:00:00,15,4,16:58:32.839000,1,8,21:40:37.624000
4,4,dkurDhelx9,2020-04-01 03:00:00+00:00,2252228,26.0,0.0,1.0,0.0,0.0,27.0,NaN,NaN,0.0,0.0,0.0,0.0,parse-cloud,_User$tkAdHTNhC9,Rio Grande do Sul,Encantado,Rio Grande do Sul,Encantado,False,2020-04-15T17:02:53.877Z,2020-08-01T21:37:53.664Z,2020,2020-04-15 17:02:53.877000+00:00,2020-08-01 21:37:53.664000+00:00,1,4,03:00:00,15,4,17:02:53.877000,1,8,21:37:53.664000

In [179]:
df = df.drop(columns=[
    'Unnamed: 0',
    'dataCriado',
    'dataAtualizado',
   
])

In [180]:
df = df.drop(columns=[
    'ocupacaoSuspeitoUti',
    'ocupacaoConfirmadoUti',
    'ocupacaoSuspeitoCli',
    'ocupacaoConfirmadoCli',
    'ocupacaoHospitalarCli',
    'ocupacaoHospitalarUti'
])

In [181]:
df.head()

,_id,data_notificacao,cnes,ocupacaoCovidUti,ocupacaoCovidCli,saidaSuspeitaObitos,saidaSuspeitaAltas,saidaConfirmadaObitos,saidaConfirmadaAltas,origem,_p_usuario,estadoNotificacao,municipioNotificacao,estado,municipio,excluido,_created_at,_updated_at,ano_origem,dia_notificacao,mes_notificacao,hora_notificao,dia_criado,mes_criado,hora_criado,dia_atualizado,mes_atualizado,hora_atualizado
0,p5Ez41Zu6B,2020-04-14 03:00:00+00:00,2303167,0.0,0.0,0.0,0.0,0.0,0.0,aplicacao-web,_User$auVMjEVEVz,Santa Catarina,Itapema,Santa Catarina,Itapema,True,2020-04-15T13:44:30.085Z,2020-04-16T13:56:13.656Z,2020,14,4,03:00:00,15,4,13:44:30.085000,16,4,13:56:13.656000
1,eUOMsSt7T7,2020-04-15 03:00:00+00:00,5935377,0.0,1.0,0.0,1.0,0.0,0.0,parse-cloud,_User$WBa5nfe9P9,Rio de Janeiro,Rio de Janeiro,Rio de Janeiro,Rio de Janeiro,False,2020-04-15T13:50:47.256Z,2020-08-01T20:08:13.116Z,2020,15,4,03:00:00,15,4,13:50:47.256000,1,8,20:08:13.116000
2,QaG4oIBrMa,2020-04-15 14:57:16.255000+00:00,12599,3.0,18.0,0.0,0.0,0.0,0.0,parse-cloud,_User$6oxZQHBPQ7,Rio de Janeiro,Niterói,Rio de Janeiro,Niterói,False,2020-04-15T15:20:57.033Z,2020-08-01T20:02:12.729Z,2020,15,4,14:57:16.255000,15,4,15:20:57.033000,1,8,20:02:12.729000
3,ifya31F3ZF,2020-03-24 03:00:00+00:00,2562871,0.0,10.0,0.0,0.0,0.0,0.0,parse-cloud,_User$fhufIbmR9C,Ceará,Várzea Alegre,Ceará,Várzea Alegre,False,2020-04-15T16:58:32.839Z,2020-08-01T21:40:37.624Z,2020,24,3,03:00:00,15,4,16:58:32.839000,1,8,21:40:37.624000
4,dkurDhelx9,2020-04-01 03:00:00+00:00,2252228,0.0,27.0,0.0,0.0,0.0,0.0,parse-cloud,_User$tkAdHTNhC9,Rio Grande do Sul,Encantado,Rio Grande do Sul,Encantado,False,2020-04-15T17:02:53.877Z,2020-08-01T21:37:53.664Z,2020,1,4,03:00:00,15,4,17:02:53.877000,1,8,21:37:53.664000

# Conectando

In [ ]:
%pip install sqlalchemy
%pip install psycopg2-binary

In [190]:
colunas_hospital = ['cnes','estado','municipio']

dim_hospital = df[colunas_hospital].drop_duplicates().reset_index(drop=True)
dim_hospital = dim_hospital.reset_index().rename(columns={'index': 'id_hospital_sk'})

print(f"Dimensão Hospital: {len(dim_hospital)} perfis")

colunas_notificacao = ['origem','_p_usuario','estadoNotificacao','municipioNotificacao']

dim_notificacao = df[colunas_notificacao].drop_duplicates().reset_index(drop=True)
dim_notificacao = dim_notificacao.reset_index().rename(columns={'index': 'id_notificacao_sk'})

print(f"Dimensão Notificação: {len(dim_notificacao)} perfis")

colunas_tempo = ['data_notificacao','created_at','updated_at','ano_origem','dia_notificacao','mes_notificacao','hora_notificao','dia_criado','mes_criado','hora_criado','dia_atualizado','mes_atualizado','hora_atualizado']

dim_tempo = df[colunas_tempo].drop_duplicates().reset_index(drop=True)
dim_tempo = dim_tempo.reset_index().rename(columns={'index': 'id_tempo_sk'})

print(f"Dimensão Tempo: {len(dim_tempo)} perfis")

Dimensão Hospital: 4508 perfis
Dimensão Notificação: 6558 perfis
Dimensão Tempo: 1589866 perfis

In [191]:
dim_hospital.head()

   id_hospital_sk     cnes             estado       municipio
0               0  2303167     Santa Catarina         Itapema
1               1  5935377     Rio de Janeiro  Rio de Janeiro
2               2    12599     Rio de Janeiro         Niterói
3               3  2562871              Ceará   Várzea Alegre
4               4  2252228  Rio Grande do Sul       Encantado

In [192]:
dim_tempo.head()

,id_tempo_sk,data_notificacao,created_at,updated_at,ano_origem,dia_notificacao,mes_notificacao,hora_notificao,dia_criado,mes_criado,hora_criado,dia_atualizado,mes_atualizado,hora_atualizado
0,0,2020-04-14 03:00:00+00:00,2020-04-15T13:44:30.085Z,2020-04-16T13:56:13.656Z,2020,14,4,03:00:00,15,4,13:44:30.085000,16,4,13:56:13.656000
1,1,2020-04-15 03:00:00+00:00,2020-04-15T13:50:47.256Z,2020-08-01T20:08:13.116Z,2020,15,4,03:00:00,15,4,13:50:47.256000,1,8,20:08:13.116000
2,2,2020-04-15 14:57:16.255000+00:00,2020-04-15T15:20:57.033Z,2020-08-01T20:02:12.729Z,2020,15,4,14:57:16.255000,15,4,15:20:57.033000,1,8,20:02:12.729000
3,3,2020-03-24 03:00:00+00:00,2020-04-15T16:58:32.839Z,2020-08-01T21:40:37.624Z,2020,24,3,03:00:00,15,4,16:58:32.839000,1,8,21:40:37.624000
4,4,2020-04-01 03:00:00+00:00,2020-04-15T17:02:53.877Z,2020-08-01T21:37:53.664Z,2020,1,4,03:00:00,15,4,17:02:53.877000,1,8,21:37:53.664000

In [186]:
dim_notificacao.head()

,id_notificacao_sk,origem,_p_usuario,estadoNotificacao,municipioNotificacao
0,0,aplicacao-web,_User$auVMjEVEVz,Santa Catarina,Itapema
1,1,parse-cloud,_User$WBa5nfe9P9,Rio de Janeiro,Rio de Janeiro
2,2,parse-cloud,_User$6oxZQHBPQ7,Rio de Janeiro,Niterói
3,3,parse-cloud,_User$fhufIbmR9C,Ceará,Várzea Alegre
4,4,parse-cloud,_User$tkAdHTNhC9,Rio Grande do Sul,Encantado

In [187]:
fato = df.merge(dim_hospital, on=colunas_hospital, how='left')
fato = fato.merge(dim_notificacao, on=colunas_notificacao, how='left')
fato = fato.merge(dim_tempo, on=colunas_tempo, how='left')

#Pegando apenas os IDs e os dados 
colunas_fato = [
    'id_hospital_sk', 
    'id_notificacao_sk',
    'id_tempo_sk', 
    'ocupacaoCovidUti',
    'ocupacaoCovidCli',
    'saidaSuspeitaObitos',
    'saidaSuspeitaAltas',
    'saidaConfirmadaObitos',
    'saidaConfirmadaAltas'
]

fato_covid = fato[colunas_fato]
print(f"Fato pronta: {len(fato_covid)} registros.")

Fato pronta: 1589874 registros.

In [ ]:
from sqlalchemy import create_engine

# Configurando a conexão
usuario_db = ''               
senha_db = ''                
host_db = ''                    
porta_db = ''                    
nome_banco_db = ''         

# Criando a "connection string"
DATABASE_URL = f'postgresql://{usuario_db}:{senha_db}@{host_db}:{porta_db}/{nome_banco_db}?client_encoding=utf8'
print("Tentando criar conexão com o banco...")

try:
    engine = create_engine(DATABASE_URL)
    print("Conexão bem-sucedida! Iniciando a carga do Esquema Estrela...")
    
    print("Carregando Dimensão Hospital...")
    dim_hospital.to_sql('dim_hospital', con=engine, if_exists='replace', index=False)
    
    print("Carregando Dimensão Notificacao...")
    dim_notificacao.to_sql('dim_notificacao', con=engine, if_exists='replace', index=False)
    
    print("Carregando Dimensão Tempo...")
    dim_tempo.to_sql('dim_tempo', con=engine, if_exists='replace', index=False)
    
   

    
    print("Carregando Tabela Fato...")
    fato_covid.to_sql('fato_covid', con=engine, if_exists='replace', index=False)

    print("\nCARGA CONCLUÍDA! Todas as 6 tabelas do Esquema Estrela foram criadas.")

except Exception as e:
    print(f"\n--- ERRO! ---")
    print(f"Erro ao carregar os dados: {e}")

Tentando criar conexão com o banco...
Conexão bem-sucedida! Iniciando a carga do Esquema Estrela...
Carregando Dimensão Hospital...
Carregando Dimensão Notificacao...
Carregando Dimensão Tempo...
Carregando Tabela Fato...

CARGA CONCLUÍDA! Todas as 6 tabelas do Esquema Estrela foram criadas.